
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import com.mysql.cj.xdevapi.Table;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import static javax.swing.UIManager.getInt;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC
 */
public class NewJFrame8 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame8
     */
    public NewJFrame8() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 590));

        jPanel1.setLayout(null);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(290, 190, 290, 40);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(290, 250, 290, 40);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(290, 310, 290, 40);
        jPanel1.add(jTextField6);
        jTextField6.setBounds(430, 530, 200, 22);
        jPanel1.add(jTextField7);
        jTextField7.setBounds(280, 360, 110, 22);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(480, 360, 110, 22);
        jPanel1.add(jTextField5);
        jTextField5.setBounds(70, 360, 110, 22);

        jLabel3.setText("Mois N° :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 360, 50, 16);

        jLabel4.setText("Année :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(407, 360, 50, 16);

        jLabel5.setText("jour :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 360, 27, 16);

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton1.setText("Insertion");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(730, 160, 160, 40);

        jToggleButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton2.setText("Reset");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2);
        jToggleButton2.setBounds(730, 220, 160, 40);

        jToggleButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton3.setText("Retour");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton3);
        jToggleButton3.setBounds(730, 290, 160, 40);

        jToggleButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton4.setText("Terminé");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton4);
        jToggleButton4.setBounds(733, 500, 160, 40);

        jToggleButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton8.setText("Calcule prix");
        jToggleButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton8);
        jToggleButton8.setBounds(730, 360, 160, 40);

        jToggleButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jToggleButton9.setText("Imprimer Facture");
        jToggleButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton9MouseClicked(evt);
            }
        });
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton9);
        jToggleButton9.setBounds(730, 430, 160, 40);

        jToggleButton5.setText("envoyer par gmail");
        jPanel1.add(jToggleButton5);
        jToggleButton5.setBounds(730, 470, 160, 25);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Le montatnt globale est :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(250, 530, 170, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "désignation", "qte", "prix"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 390, 600, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\8.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        NewJFrame3 Variable = new NewJFrame3();
        Variable.show();
        dispose();
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String passwd="";
            String user="root";
            String url="jdbc:mysql://localhost:3306/utilsateur";
            Connection con = java.sql.DriverManager.getConnection(url,user,passwd);
            PreparedStatement pst = con.prepareStatement("SELECT Qte,prix FROM produit WHERE désignation=?");
            pst.setString(1,jTextField1.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                String chaine1 = jTextField2.getText();
                int i = Integer.parseInt(chaine1);
            
            int j = rs.getInt("Qte");
            int p = rs.getInt("prix");
            
                if(i <= j){
                    //insertion dans la table commande
                    try{
                    pst =con.prepareStatement("INSERT INTO commande(désignation,Qte,prix) VALUES (?,?,?)");
                    int resultat = p*i;
                    Integer rr = resultat;
                    String Chaine3 = rr.toString();
                    pst.setString(1,jTextField1.getText());
                    pst.setString(2,jTextField2.getText());
                    pst.setString(3,Chaine3);
                    pst.executeUpdate();
                    //modification dans la table produit
                    j=j-i;
                    try{
                    pst = con.prepareStatement("UPDATE produit SET Qte=? WHERE désignation=?");
                    pst.setString(2,jTextField1.getText());
                    rr = j;
                    Chaine3 = rr.toString();
                    pst.setString(1,Chaine3);
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Record modified");
                    } 
                    catch(SQLException | HeadlessException ex){
                    JOptionPane.showMessageDialog(null,ex);
                    }
                    ////////////////////////////////////////////////////////////
                    try{
                        con = java.sql.DriverManager.getConnection(url,user,passwd);
                        pst = con.prepareStatement("SELECT qte,prix FROM bilan WHERE désignation=? and mois=? and année=?");
                        pst.setString(1,jTextField1.getText());
                        pst.setString(2,jTextField7.getText());
                        pst.setString(3,jTextField4.getText());
                        rs = pst.executeQuery();
                        if(rs.next()){
                        int q = rs.getInt("Qte");
                        int r = rs.getInt("prix"); 
                        q=q+i;
                        r=r+resultat;
                        try{
                            pst = con.prepareStatement("UPDATE bilan SET qte=? , prix=? WHERE désignation=? and mois=? and année=?");
                            pst.setString(3,jTextField1.getText());
                            pst.setString(4,jTextField7.getText());
                            pst.setString(5,jTextField4.getText());
                            
                            rr = q;
                            String Chaine4 = rr.toString();
                            pst.setString(1,Chaine4);
                        
                            rr = r;
                            String Chaine5 = rr.toString();
                            pst.setString(2,Chaine5);
                            
                            pst.executeUpdate();
                        }
                        catch(SQLException | HeadlessException ex){
                            JOptionPane.showMessageDialog(null,ex);
                        }
                    }
                    else{
                            //insertion f la table bilan
                            try{
                                pst =con.prepareStatement("INSERT INTO bilan(désignation,qte,prix,mois,année) VALUES (?,?,?,?,?)");
                                
                                int a = resultat;
                                rr = a;
                                String Chaine4 = rr.toString();
                                pst.setString(1,jTextField1.getText());
                                pst.setString(2,jTextField2.getText());
                                pst.setString(3,Chaine4);
                                pst.setString(4,jTextField7.getText());
                                pst.setString(5,jTextField4.getText());
                                pst.executeUpdate();
                            }
                            catch (SQLException ex){
                                JOptionPane.showMessageDialog(null, ex);
                            }   
                    }
                    }
                    catch (SQLException ex){
                    JOptionPane.showMessageDialog(null, ex);
                    }
                    ////////////////////////////////////////////////////////////
                    }
                    catch(SQLException | HeadlessException ex){
                    JOptionPane.showMessageDialog(null,ex);
                    }
                    JOptionPane.showMessageDialog(null,"Record added");
                    }
                    else{
                    JOptionPane.showMessageDialog(null,"Stock insuffisant");
                    }
            }
            else{
                JOptionPane.showMessageDialog(null, "produit n existe pas");
            }
            try{
                pst =con.prepareStatement("select * from commande");
                rs = pst.executeQuery();
                ResultSetMetaData stData = (ResultSetMetaData) rs.getMetaData();
                int q = stData.getColumnCount();
                DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
                RecordTable.setRowCount(0);
                while(rs.next()){
                    Vector columnData = new Vector();
                    for(int i=1;i<q;i++){
                        columnData.add(rs.getString("désignation"));
                        columnData.add(rs.getString("Qte"));
                        columnData.add(rs.getString("prix"));
                    } 
                    RecordTable.addRow(columnData);  
                }  
            }
            catch (SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
            
        }
        catch (SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)jTable1.getModel();
        int SelectedRows = jTable1.getSelectedRow();
        jTextField1.setText(RecordTable.getValueAt(SelectedRows,0).toString());
        jTextField2.setText(RecordTable.getValueAt(SelectedRows,1).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        // TODO add your handling code here:
        try{
            String passwd="";
            String user="root";
            String url="jdbc:mysql://localhost:3306/utilsateur";
            Connection con = java.sql.DriverManager.getConnection(url,user,passwd);
            PreparedStatement pst = con.prepareStatement("SELECT * FROM commande");
            ResultSet rs = pst.executeQuery();
            int s=0;
            int i;
            while(rs.next()){
               i=rs.getInt("prix");
               s=s+i;
            }
            ////////////////////////////////////////////////////////////////////
            try{
            con = java.sql.DriverManager.getConnection(url,user,passwd);
            pst=con.prepareStatement("SELECT revendeur FROM client WHERE numéro = ? ");      
            pst.setString(1,jTextField3.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                String Chaine1 ="non";
                String A = rs.getString("revendeur");
                if(Chaine1.equals(A)){
                   s =  (int) (s*1.2);
                }
                //réduction
                if(s>=1000){
                    s=(int)(s*0.95);
                }
                Integer rr = s;
                String Chaine3 = rr.toString();
                jTextField6.setText(Chaine3);
                ////////////////////////////////////////////////////////////////
                try{
                con = java.sql.DriverManager.getConnection(url,user,passwd);
                pst =con.prepareStatement("INSERT INTO historique(numéro,montant,mois,année,jour) VALUES (?,?,?,?,?)");
                pst.setString(1,jTextField3.getText());
                pst.setString(2,Chaine3);
                pst.setString(3,jTextField7.getText());
                pst.setString(4,jTextField4.getText());
                pst.setString(5,jTextField5.getText());
                pst.executeUpdate();
                ////////////////////////////////////////////////////////////////
                try{
                        con = java.sql.DriverManager.getConnection(url,user,passwd);
                        pst = con.prepareStatement("SELECT montant FROM sauvegarde WHERE mois=? and année=?");
                        pst.setString(1,jTextField7.getText());
                        pst.setString(2,jTextField4.getText());
                        rs = pst.executeQuery();
                        if(rs.next()){
                        int q = rs.getInt("montant");
                        q = q+s;
                        try{
                            pst = con.prepareStatement("UPDATE sauvegarde SET montant=? WHERE mois=? and année=?");
                            pst.setString(2,jTextField7.getText());
                            pst.setString(3,jTextField4.getText());
                            rr = q;
                            String Chaine4 = rr.toString();
                            pst.setString(1,Chaine4);
                            pst.executeUpdate();
                        }
                        catch(SQLException | HeadlessException ex){
                            JOptionPane.showMessageDialog(null,ex);
                        }
                        }
                        else{
                            try{
                                pst =con.prepareStatement("INSERT INTO sauvegarde(montant,mois,année) VALUES (?,?,?)");
                                pst.setString(1,Chaine3);
                                pst.setString(2,jTextField7.getText());
                                pst.setString(3,jTextField4.getText());
                                
                                pst.executeUpdate();
                            }
                            catch (SQLException ex){
                                JOptionPane.showMessageDialog(null, ex);
                            }    
                        }
                    }
                    catch (SQLException ex){
                    JOptionPane.showMessageDialog(null, ex);
                    }
                ////////////////////////////////////////////////////////////////
                }
                catch(SQLException | HeadlessException ex){
                    JOptionPane.showMessageDialog(null,ex);
                }
                ////////////////////////////////////////////////////////////////
            }
            else{
               JOptionPane.showMessageDialog(null,"erreur");
            }
            }
            catch (SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        catch (SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jToggleButton8ActionPerformed

    private void jToggleButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton8MouseClicked

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Facture du client"+jTextField3.getText()+",Le Totale est:"+jTextField6.getText()+"DA");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        MessageFormat debut = new MessageFormat("Facture");
        try{
            jTable1.print(JTable.PrintMode.FIT_WIDTH,header,footer);
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur:\n"+e,"impression",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton9MouseClicked

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
        String passwd="";
        String user="root";
        String url="jdbc:mysql://localhost:3306/utilsateur";
        try{
            String sql =("delete from commande");
            Connection con = DriverManager.getConnection(url,user,passwd);
            PreparedStatement pst = con.prepareStatement(sql);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Delete successfully");
            ////////////////////////////////////////////////////////////////////////////////////////////
            try{
                con = DriverManager.getConnection(url,user,passwd);
                pst =con.prepareStatement("select * from commande");
                ResultSet rs = pst.executeQuery();
                ResultSetMetaData stData = (ResultSetMetaData) rs.getMetaData();
                int q = stData.getColumnCount();
                DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
                RecordTable.setRowCount(0);
                while(rs.next()){
                    Vector columnData = new Vector();
                    int i;
                    for(i=1;i<q;i++){
                        columnData.add(rs.getString("désignation"));
                        columnData.add(rs.getString("Qte"));
                        columnData.add(rs.getString("prix"));
                    } 
                    RecordTable.addRow(columnData);  
                }
                
            }
            catch (SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
            ////////////////////////////////////////////////////////////////////////////////////////////
            jTextField1.setText(null);
            jTextField2.setText(null);
            jTextField3.setText(null);
            jTextField6.setText(null);
          
        }catch (SQLException | HeadlessException ex) {
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame8.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame8().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables

    private String setText(String string) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
