
import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC
 */
public class NewJFrame5 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame5
     */
    public NewJFrame5() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1004, 590));

        jPanel1.setLayout(null);

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton1.setText("Bilan de vente");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(90, 150, 180, 50);

        jToggleButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton2.setText("Sauvegarde");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2);
        jToggleButton2.setBounds(370, 150, 180, 50);

        jToggleButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton3.setText("Comparer");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton3);
        jToggleButton3.setBounds(430, 460, 180, 50);

        jToggleButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButton4.setText("Retour");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton4);
        jToggleButton4.setBounds(780, 460, 180, 50);

        jToggleButton5.setText("modifier plan");
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton5);
        jToggleButton5.setBounds(730, 150, 180, 40);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(340, 470, 80, 22);

        jLabel3.setText("montant");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(640, 200, 50, 16);

        jLabel4.setText("mois");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(830, 200, 37, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Année :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(257, 520, 50, 20);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mois :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(270, 480, 40, 16);
        jPanel1.add(jTextField2);
        jTextField2.setBounds(690, 200, 100, 22);
        jPanel1.add(jTextField3);
        jTextField3.setBounds(880, 200, 90, 22);
        jPanel1.add(jTextField4);
        jTextField4.setBounds(343, 520, 80, 22);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "désignation", "Qte", "prix", "mois", "année"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 230, 270, 210);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "montant", "mois", "annéé"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(320, 230, 280, 210);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "montant", "mois"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(630, 230, 340, 210);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\PC\\Desktop\\10.png")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1004, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String passwd="";
            String user="root";
            String url="jdbc:mysql://localhost:3306/utilsateur";
            Connection con = java.sql.DriverManager.getConnection(url,user,passwd);
            PreparedStatement pst = con.prepareStatement("select * from bilan");
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData stData = (ResultSetMetaData) rs.getMetaData();
            int q = stData.getColumnCount();
            DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
            RecordTable.setRowCount(0);
            while(rs.next()){
                Vector columnData = new Vector();
                for(int i=1;i<q;i++){
                columnData.add(rs.getString("désignation"));
                columnData.add(rs.getString("qte"));
                columnData.add(rs.getString("prix"));
                columnData.add(rs.getString("mois"));
                columnData.add(rs.getString("année"));
                } 
                RecordTable.addRow(columnData);  
            }  
        }
            catch (SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        try{
            String passwd="";
            String user="root";
            String url="jdbc:mysql://localhost:3306/utilsateur";
            Connection con = java.sql.DriverManager.getConnection(url,user,passwd);
            PreparedStatement pst = con.prepareStatement("select * from sauvegarde");
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData stData = (ResultSetMetaData) rs.getMetaData();
            int q = stData.getColumnCount();
            DefaultTableModel RecordTable = (DefaultTableModel) jTable2.getModel();
            RecordTable.setRowCount(0);
            while(rs.next()){
                Vector columnData = new Vector();
                for(int i=1;i<q;i++){
                columnData.add(rs.getString("montant"));
                columnData.add(rs.getString("mois"));
                columnData.add(rs.getString("année"));
                } 
                RecordTable.addRow(columnData);  
            }  
        }
            catch (SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
        NewJFrame1 Variable = new NewJFrame1();
        Variable.show();
        dispose();
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        String passwd="";
        String user="root";
        String url="jdbc:mysql://localhost:3306/utilsateur";
        try{
            Connection con = DriverManager.getConnection(url,user,passwd);
            PreparedStatement pst = con.prepareStatement("SELECT montant FROM sauvegarde WHERE mois=? and année=?");
            pst.setString(1,jTextField1.getText());
            pst.setString(2,jTextField4.getText());
            ResultSet rs = pst.executeQuery();
            if(rs.next()){
                int q = rs.getInt("montant");
                try{
                    con = DriverManager.getConnection(url,user,passwd);
                    pst = con.prepareStatement("SELECT montant FROM plan WHERE mois=?");
                    pst.setString(1,jTextField1.getText());
                    ResultSet rsl = pst.executeQuery();
                    if(rsl.next()){
                        int r = rsl.getInt("montant");
                        if(q<r){
                            JOptionPane.showMessageDialog(null,"chiffre d affaire est petit parapour à celui prévu initialement");
                        }
                        else if(q>r){
                            JOptionPane.showMessageDialog(null,"chiffre d affaire est grand parapour à celui prévu initialement");
                        }
                        else{
                            JOptionPane.showMessageDialog(null,"chiffre d affaire est egale parapour à celui prévu initialement"); 
                        }
                    }
                    
                }
                catch(SQLException ex){
                    JOptionPane.showMessageDialog(null, ex);
                }
            }
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)jTable3.getModel();
        int SelectedRows = jTable3.getSelectedRow();
        jTextField2.setText(RecordTable.getValueAt(SelectedRows,0).toString());
        jTextField3.setText(RecordTable.getValueAt(SelectedRows,1).toString());
    }//GEN-LAST:event_jTable3MouseClicked

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
        try{
            String sql="UPDATE plan SET montant=? WHERE mois=?";
            String passwd="";
            String user="root";
            String url="jdbc:mysql://localhost:3306/utilsateur";
            Connection con = DriverManager.getConnection(url,user,passwd);
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(2,jTextField3.getText());
            pst.setString(1,jTextField2.getText());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Record modified");
            ////////////////////////////////////////////////////////////////////////////////////////////
            try{
                con = DriverManager.getConnection(url,user,passwd);
                pst =con.prepareStatement("select * from plan");
                ResultSet rs = pst.executeQuery();
                ResultSetMetaData stData = (ResultSetMetaData) rs.getMetaData();
                int q = stData.getColumnCount();
                DefaultTableModel RecordTable = (DefaultTableModel) jTable3.getModel();
                RecordTable.setRowCount(0);
                while(rs.next()){
                    Vector columnData = new Vector();
                    int i;
                    for(i=1;i<q;i++){
                        columnData.add(rs.getString("montant"));
                        columnData.add(rs.getString("mois"));
                    } 
                    RecordTable.addRow(columnData);  
                }  
            }
            catch (SQLException ex){
                JOptionPane.showMessageDialog(null, ex);
            }
        }
        catch(SQLException | HeadlessException ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    // End of variables declaration//GEN-END:variables
}
